[package]
name = "doubly-linked-list"
version = "0.1.0"
authors = ["Andres Aguirre <aguirregzz97@gmail.com>","Sandro Skhirtladze <sandrosxila@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
